(function(){
const APP_VERSION='2.4.0', $=id=>document.getElementById(id),input=$('eqs'),status=$('status'),methods=$('methods'),solve=$('solve'),out=$('out'),detected=$('detectedType');
let size=3,mode='auto',manualKind='system',parsed=null,problemKind=null,methodId='adicion',lastResult=null,lastSystem=null;let settings={typing:true,haptic:true,autoUpdate:true};try{settings=Object.assign(settings,JSON.parse(localStorage.getItem('algebra-settings')||'{}'))}catch(_){localStorage.removeItem('algebra-settings')}
const sleep=ms=>new Promise(r=>setTimeout(r,ms)), haptic=()=>settings.haptic&&navigator.vibrate&&navigator.vibrate(8), saveSettings=()=>localStorage.setItem('algebra-settings',JSON.stringify(settings));
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3600)}
function detect(){const text=input.value.trim();if(!text)return null;if(/[xX](?:\^2|²)/.test(text))return'quadratic';const lines=text.split(/\n+/).filter(x=>x.trim()).length, vars=[...new Set((text.toLowerCase().match(/[xyz]/g)||[]))];if(lines===2||vars.length===2)return'system2';if(lines===3||vars.length>=3)return'system3';return null}
function currentKind(){if(mode==='auto')return detect();return manualKind==='quadratic'?'quadratic':'system'+size}
function setStatus(ok,msg){status.className='status '+(ok?'ok':'err');status.textContent=msg}
function buildMethods(){methods.innerHTML='';let list=problemKind==='quadratic'?Object.values(QUADRATIC_METHODS):Object.values(METHODS);if(!list.some(x=>x.id===methodId))methodId=list[0]?.id||'';list.forEach(m=>{const b=document.createElement('button');b.className='chip'+(m.id===methodId?' on':'');b.textContent=m.name;b.onclick=()=>{methodId=m.id;buildMethods()};methods.appendChild(b)})}
function validate(){const kind=currentKind();if(!input.value.trim()){parsed=null;problemKind=null;methods.innerHTML='';solve.disabled=true;detected.textContent='Esperando ecuaciones';status.className='status';status.textContent='Escribe una ecuación o un sistema para comenzar.';return}if(!kind){parsed=null;methods.innerHTML='';solve.disabled=true;detected.textContent='Analizando…';setStatus(false,'No se pudo identificar todavía el tipo de problema.');return}problemKind=kind;detected.textContent=kind==='quadratic'?'Detectado: ecuación cuadrática':`Detectado: sistema ${kind==='system2'?'2×2':'3×3'}`;if(kind==='quadratic')parsed=parseQuadratic(input.value);else parsed=parseSystem(input.value,kind==='system2'?2:3);if(!parsed.ok){methods.innerHTML='';solve.disabled=true;setStatus(false,parsed.error);return}buildMethods();solve.disabled=false;setStatus(true,kind==='quadratic'?'Ecuación cuadrática lista para resolver.':`Sistema ${parsed.size}×${parsed.size} listo para resolver.`)}
input.addEventListener('input',validate);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('on',x===b));$('manualControls').classList.toggle('hidden',mode!=='manual');validate()});document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{size=+b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('on',x===b));validate()});document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{manualKind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('on',x===b));$('systemSizeControls').classList.toggle('hidden',manualKind==='quadratic');validate()});
function filterSteps(steps,level){if(level==='complete'||level==='detailed')return steps;return steps.filter((s,i)=>s.titulo==='Resultado'||i===0||i%2===1)}
async function typeText(el,text){if(!settings.typing){el.textContent=text;return}for(const c of text){el.textContent+=c;await sleep(c===' '?7:13)}}
function verification(sys,result){if(problemKind==='quadratic'||!result.ok||!result.sol)return null;return{titulo:'Comprobación',markdown:'Las soluciones se verifican sustituyendo sus valores en las ecuaciones originales.\n\n$$'+sys.vars.map((v,i)=>v+'='+result.sol[i].toString()).join('\\quad')+'$$'}}
async function renderResult(result,sys){out.innerHTML='';const steps=filterSteps(result.steps,$('detailLevel').value);const check=verification(sys,result);if(check)steps.push(check);for(const s of steps){const a=document.createElement('article'),h=document.createElement('h2'),c=document.createElement('div');a.className='solution-step';c.className='step-content';c.innerHTML=renderMarkdown(s.markdown);a.append(h,c);out.appendChild(a);await typeText(h,s.titulo);haptic();if(settings.typing)await sleep(Math.min(280,90+s.markdown.length*.35))}}
function historyMeta(){return problemKind==='quadratic'?'Ecuación cuadrática':`Sistema ${parsed.size}×${parsed.size}`}
function saveHistory(){let all=[];try{all=JSON.parse(localStorage.getItem('algebra-history')||'[]');if(!Array.isArray(all))all=[]}catch(_){}all.unshift({id:Date.now(),input:input.value,kind:problemKind,size:parsed.size||null,method:problemKind==='quadratic'?QUADRATIC_METHODS[methodId].name:METHODS[methodId].name,date:new Date().toLocaleString('es-419')});localStorage.setItem('algebra-history',JSON.stringify(all.slice(0,50)));renderHistory()}
solve.onclick=async()=>{validate();if(!parsed?.ok)return;solve.disabled=true;solve.textContent='Resolviendo…';try{const r=problemKind==='quadratic'?solveQuadratic(parsed,methodId):solveSystem(parsed,methodId);lastResult=r;lastSystem=parsed;await renderResult(r,parsed);saveHistory()}catch(e){out.innerHTML='<article class="solution-step"><h2>Error</h2><div class="step-content">'+String(e.message||e)+'</div></article>'}finally{solve.disabled=false;solve.innerHTML='<svg viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>Resolver'}};
function renderHistory(){const box=$('historyList');let all=[];try{all=JSON.parse(localStorage.getItem('algebra-history')||'[]');if(!Array.isArray(all))all=[]}catch(_){}if(!all.length){box.innerHTML='<div class="empty-state"><strong>Aún no hay resoluciones</strong><span>Las soluciones que realices aparecerán aquí.</span></div>';return}box.innerHTML='';all.forEach(item=>{const b=document.createElement('button');b.className='history-card';b.innerHTML='<strong>'+item.method+' · '+(item.kind==='quadratic'?'Cuadrática':(item.size+'×'+item.size))+'</strong><span>'+item.input.replace(/</g,'&lt;').replace(/\n/g,' · ')+'</span><span>'+item.date+'</span>';b.onclick=()=>{input.value=item.input;mode='auto';document.querySelector('[data-mode="auto"]').click();document.querySelector('[data-tab="resolver"]').click();validate();toast('Ejercicio restaurado.')};box.appendChild(b)})}
function plainSolution(){if(!lastResult)return null;if(problemKind==='quadratic')return(lastResult.roots||[]).map((x,i)=>'x'+(i+1)+' = '+(typeof x==='number'?x:JSON.stringify(x))).join('\n');if(lastResult.sol)return lastResult.sol.map((v,i)=>lastSystem.vars[i]+' = '+v.toString()).join('\n');return null}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=async()=>{const text=plainSolution();if(!text)return toast('Primero resuelve un ejercicio.');if(b.dataset.tool==='copy'){try{await navigator.clipboard.writeText(text);toast('Solución copiada.')}catch(_){toast('No se pudo acceder al portapapeles.')}}else if(navigator.share){await navigator.share({title:'Álgebra',text})}else toast('Tu navegador no permite compartir.')});
function switchTab(name){document.querySelectorAll('.tab-page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='historial')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
[['typingToggle','typing'],['hapticToggle','haptic'],['autoUpdateToggle','autoUpdate']].forEach(([id,key])=>{const e=$(id);e.checked=settings[key];e.onchange=()=>{settings[key]=e.checked;saveSettings()}});
// Splash and lifecycle: never leave an invisible overlay intercepting touches.
function start(){const s=$('splash'),shell=$('appShell');setTimeout(()=>{if(s){s.classList.add('leaving');s.style.pointerEvents='none'}if(shell)shell.classList.add('ready');setTimeout(()=>s?.remove(),900)},2400)}
window.addEventListener('pageshow',()=>{const s=$('splash');if(s){s.style.pointerEvents='none';s.remove()}$('appShell')?.classList.add('ready')});document.addEventListener('visibilitychange',()=>{if(!document.hidden)$('appShell')?.classList.add('ready')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});start();try{renderHistory();validate()}catch(e){console.error(e);$('appShell')?.classList.add('ready')}
})();