(function(){
const APP_VERSION='2.3.0'; const $=id=>document.getElementById(id); const input=$('eqs'),status=$('status'),methods=$('methods'),solve=$('solve'),out=$('out'),detected=$('detectedType');
let size=3,mode='auto',parsed=null,methodId='adicion',lastResult=null,lastSystem=null;
let storedSettings={};
try{storedSettings=JSON.parse(localStorage.getItem('algebra-settings')||'{}')||{}}catch(_){localStorage.removeItem('algebra-settings')}
let settings=Object.assign({typing:true,haptic:true,autoUpdate:true},storedSettings);
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const haptic=()=>settings.haptic&&navigator.vibrate&&navigator.vibrate(8); const saveSettings=()=>localStorage.setItem('algebra-settings',JSON.stringify(settings));
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3800)}
function detectSize(){const lines=input.value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const vars=[...new Set((input.value.toLowerCase().match(/[xyz]/g)||[]))];if(vars.includes('z')||lines.length===3||vars.length>=3)return 3;if(lines.length===2||vars.length===2)return 2;return null}
function effectiveSize(){return mode==='auto'?(detectSize()||size):size}
function validate(){const d=detectSize(),n=effectiveSize();detected.textContent=mode==='auto'?(d?`Detectado: sistema ${d}×${d}`:'Escribe las ecuaciones para detectar el problema'):`Selección manual: sistema ${size}×${size}`;if(!input.value.trim()){parsed=null;methods.innerHTML='';solve.disabled=true;status.className='status';status.textContent='Escribe las ecuaciones para comenzar.';return}const lines=input.value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const incomplete=lines.find((line,i)=>!line.includes('=')?`La ecuación ${i+1} parece incompleta: falta el signo =.`:null);if(incomplete){parsed=null;methods.innerHTML='';solve.disabled=true;status.className='status err';status.textContent=incomplete;return}parsed=parseSystem(input.value,n);methods.innerHTML='';if(!parsed.ok){solve.disabled=true;status.className='status err';status.textContent=parsed.error;return}status.className='status ok';status.textContent=`Sistema ${n}×${n} listo para resolver.`;Object.values(METHODS).forEach(m=>{const b=document.createElement('button');b.className='chip'+(m.id===methodId?' on':'');b.textContent=m.name;b.onclick=()=>{methodId=m.id;validate()};methods.appendChild(b)});solve.disabled=false}
input.addEventListener('input',validate);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('on',x===b));$('manualControls').classList.toggle('hidden',mode!=='manual');validate()});document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{size=+b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('on',x===b));validate()});
function filterSteps(steps,level){if(level==='complete')return steps;if(level==='detailed')return steps;const keep=[];steps.forEach((s,i)=>{if(s.titulo==='Resultado'||i===0||i%2===1)keep.push(s)});return keep}
async function typeText(el,text){if(!settings.typing){el.textContent=text;return}for(const c of text){el.textContent+=c;await sleep(c===' '?8:18)}}
function fracDisplay(v){const n=v.toNumber();if(v.d===1)return v.toString();return `${v.toString()} ≈ ${n.toFixed(6).replace(/0+$/,'').replace(/\.$/,'').replace('.',',')}`}
function verification(sys,result){if(!result.ok||!result.sol)return null;const lines=sys.A.map((row,i)=>{let sum=new Frac(0,1);const parts=[];row.forEach((c,j)=>{const term=c.mul(result.sol[j]);sum=sum.add(term);parts.push(`${c.toString()}·${result.sol[j].toString()}`)});return {i,parts:parts.join(' + '),sum:sum.toString(),target:sys.b[i].toString(),ok:sum.eq(sys.b[i])}});return {titulo:'Comprobación',markdown:lines.map(x=>`**E${x.i+1}:** $$${x.parts}=${x.sum}=${x.target}\quad ${x.ok?'✓':'✗'}$$`).join('\n\n')}}
async function renderResult(result,sys){out.innerHTML='';const level=$('detailLevel').value;const steps=filterSteps(result.steps,level);const check=verification(sys,result);if(check)steps.push(check);for(let i=0;i<steps.length;i++){const s=steps[i],a=document.createElement('article'),h=document.createElement('h2'),c=document.createElement('div');a.className='solution-step';c.className='step-content';c.innerHTML=renderMarkdown(s.markdown);a.append(h,c);out.appendChild(a);await typeText(h,s.titulo);haptic();if(settings.typing)await sleep(Math.min(320,100+s.markdown.length*.55))}}
function saveHistory(sys,result){const item={id:Date.now(),input:input.value,size:sys.size,method:METHODS[methodId]?.name||methodId,detail:$('detailLevel').value,date:new Date().toLocaleString('es-419'),solution:result.sol?result.sol.map(fracDisplay):[]};const all=JSON.parse(localStorage.getItem('algebra-history')||'[]');all.unshift(item);localStorage.setItem('algebra-history',JSON.stringify(all.slice(0,50)));renderHistory()}
solve.onclick=async()=>{validate();if(!parsed?.ok)return;solve.disabled=true;solve.textContent='Resolviendo…';try{const r=solveSystem(parsed,methodId);lastResult=r;lastSystem=parsed;await renderResult(r,parsed);saveHistory(parsed,r)}catch(e){out.innerHTML=`<article class="solution-step"><h2>Error</h2><div>${String(e.message||e)}</div></article>`}finally{solve.disabled=false;solve.innerHTML='<svg viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>Resolver'}};
function renderHistory(){const box=$('historyList');let all=[];try{all=JSON.parse(localStorage.getItem('algebra-history')||'[]');if(!Array.isArray(all))all=[]}catch(_){localStorage.removeItem('algebra-history')}if(!all.length){box.innerHTML='<div class="empty-state"><strong>Aún no hay resoluciones</strong><span>Las soluciones que realices aparecerán aquí.</span></div>';return}box.innerHTML='';all.forEach(item=>{const b=document.createElement('button');b.className='history-card';b.innerHTML=`<strong>${item.method} · ${item.size}×${item.size}</strong><span>${item.input.replace(/\n/g,' · ')}</span><span>${item.date}</span>`;b.onclick=()=>{input.value=item.input;size=item.size;mode='manual';document.querySelector('[data-mode="manual"]').click();validate();document.querySelector('[data-tab="resolver"]').click();toast('Ejercicio restaurado.')};box.appendChild(b)})}
function plainSolution(){if(!lastResult?.sol)return null;return lastResult.sol.map((v,i)=>`${lastSystem.vars[i]} = ${fracDisplay(v)}`).join('\n')}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=async()=>{const text=plainSolution();if(!text)return toast('Primero resuelve un ejercicio.');if(b.dataset.tool==='copy'){await navigator.clipboard?.writeText(text);toast('Solución copiada.')}else if(navigator.share){await navigator.share({title:'Álgebra',text})}else{await navigator.clipboard?.writeText(text);toast('Tu navegador no permite compartir. La solución fue copiada.')}});
function switchTab(name){document.querySelectorAll('.tab-page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='historial')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
[['typingToggle','typing'],['hapticToggle','haptic'],['autoUpdateToggle','autoUpdate']].forEach(([id,key])=>{const e=$(id);e.checked=settings[key];e.onchange=()=>{settings[key]=e.checked;saveSettings()}});
const semver=v=>String(v).replace(/^v/,'').split('.').map(Number);const newer=(a,b)=>{a=semver(a);b=semver(b);for(let i=0;i<3;i++){if(a[i]!==b[i])return a[i]>b[i]}return false};let available=null;
async function checkUpdate(silent=false){if(!navigator.onLine){if(!silent)toast('Sin conexión.');return}try{const remote=await fetch('./version.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());if(newer(remote.version,APP_VERSION)){available=await fetch(remote.updateManifest+'?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());$('updateStatus').textContent='Nueva versión v'+remote.version;if(!silent)showUpdate();else toast('Actualización disponible: v'+remote.version)}else{ $('updateStatus').textContent='Ya tienes la última versión';if(!silent)toast('Álgebra está actualizado.')}}catch(e){if(!silent)toast('No se pudo comprobar la actualización.') }}
function showUpdate(){if(!available)return;$('updateVersion').textContent='v'+available.version;$('updateSummary').textContent='Hay una nueva versión disponible. La descarga es opcional.';$('updateNotes').innerHTML=(available.notes||[]).map(n=>'<div>• '+n+'</div>').join('');$('updateDownloadArea').classList.add('hidden');$('downloadUpdate').classList.remove('hidden');$('applyUpdate').classList.add('hidden');$('updateModal').classList.remove('hidden')}$('checkUpdate').onclick=()=>checkUpdate(false);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close==='update'?'updateModal':'offlineModal').classList.add('hidden'));
function cards(container,files){container.innerHTML='';return files.map(f=>{const e=document.createElement('div');e.className='file-row';e.innerHTML=`<div class="file-circle" style="--p:0"><span>0%</span></div><div class="file-meta"><strong>${f.label||f.path}</strong><small>Calculando tamaño…</small></div>`;container.appendChild(e);return{f,e,loaded:0,total:0}})}
async function downloadFiles(files,container,ids,cacheName){const cache=await caches.open(cacheName);const rows=cards(container,files);const started=performance.now();let total=0,loaded=0;for(const row of rows){try{const h=await fetch(row.f.path,{method:'HEAD'});row.total=+(h.headers.get('content-length')||0);total+=row.total}catch(_){}}for(const row of rows){const r=await fetch(row.f.path,{cache:'no-store'});if(!r.ok)throw Error('No se pudo descargar '+row.f.label);const reader=r.body?.getReader(),chunks=[];if(reader){while(true){const q=await reader.read();if(q.done)break;chunks.push(q.value);row.loaded+=q.value.byteLength;loaded+=q.value.byteLength;paint(row,loaded,total,started,ids)}const blob=new Blob(chunks);await cache.put(new URL(row.f.path,location.href).href,new Response(blob));}else await cache.put(new URL(row.f.path,location.href).href,r.clone());if(!row.total){row.total=row.loaded;total+=row.total}paint(row,loaded,total,started,ids,true)}return cache}
function paint(row,loaded,total,started,ids,done){const pct=row.total?Math.min(100,row.loaded/row.total*100):(done?100:0),circle=row.e.querySelector('.file-circle');circle.style.setProperty('--p',pct);circle.querySelector('span').textContent=Math.round(pct)+'%';row.e.querySelector('small').textContent=`${(row.loaded/1024).toFixed(1)} KB${row.total?' / '+(row.total/1024).toFixed(1)+' KB':''}`;const overall=total?Math.min(100,loaded/total*100):0;$(ids.bar).style.width=overall+'%';$(ids.percent).textContent=Math.round(overall)+'%';const sec=(performance.now()-started)/1000;$(ids.speed).textContent=sec>0?`${(loaded/1024/sec).toFixed(1)} KB/s`:'0 KB/s'}
$('downloadUpdate').onclick=async()=>{if(!available)return;$('updateDownloadArea').classList.remove('hidden');$('downloadUpdate').disabled=true;try{await downloadFiles(available.files,$('updateFiles'),{bar:'updateOverallBar',percent:'updateOverallPercent',speed:'updateDownloadSpeed'},'algebra-update-'+available.version);localStorage.setItem('algebra-pending-update',JSON.stringify({version:available.version,cache:'algebra-update-'+available.version}));$('downloadUpdate').classList.add('hidden');$('applyUpdate').classList.remove('hidden');toast('Actualización descargada.')}catch(e){toast(String(e.message||e));$('downloadUpdate').disabled=false}};
$('applyUpdate').onclick=async()=>{const p=JSON.parse(localStorage.getItem('algebra-pending-update')||'null');if(!p)return;const reg=await navigator.serviceWorker?.ready;if(reg?.active)reg.active.postMessage({type:'ACTIVATE_DOWNLOADED_UPDATE',version:p.version,cache:p.cache});toast('Actualización preparada. Reiniciando…');setTimeout(()=>location.reload(),600)};
$('offlineBtn').onclick=async()=>{$('offlineModal').classList.remove('hidden');try{const m=await fetch('./offline-manifest.json',{cache:'no-store'}).then(r=>r.json());await downloadFiles(m.files,$('offlineFiles'),{bar:'overallBar',percent:'overallPercent',speed:'downloadSpeed'},'algebra-offline-'+APP_VERSION);$('offlineSummary').textContent='Álgebra está listo para usarse sin conexión.';toast('Modo Offline preparado.')}catch(e){$('offlineSummary').textContent=String(e.message||e)}};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});$('install').onclick=async()=>{if(!deferred)return toast('Usa la opción Instalar de tu navegador.');deferred.prompt();deferred=null};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(settings.autoUpdate&&navigator.onLine)setTimeout(()=>checkUpdate(true),2500);window.addEventListener('online',()=>settings.autoUpdate&&checkUpdate(true));
function start(){
  const s=$('splash'), shell=$('appShell');
  // La pantalla principal se prepara siempre, incluso si una función secundaria falla.
  setTimeout(()=>{
    if(s) s.classList.add('leaving');
    if(shell) shell.classList.add('ready');
    setTimeout(()=>{if(s&&s.isConnected)s.remove()},900);
  },2400);
}
// Iniciamos la transición antes de las tareas que pueden depender del almacenamiento del navegador.
start();
try{renderHistory();validate()}catch(err){
  console.error('Error de inicio de Álgebra:',err);
  const st=$('status');
  if(st){st.className='status err';st.textContent='Se produjo un error al cargar algunos datos guardados. Puedes continuar escribiendo una nueva ecuación.'}
}
// Red de seguridad: la pantalla de carga nunca debe bloquear la aplicación.
window.addEventListener('error',()=>{
  const splash=$('splash'),shell=$('appShell');
  if(splash){splash.classList.add('leaving');setTimeout(()=>{if(splash.isConnected)splash.remove()},250)}
  if(shell)shell.classList.add('ready');
});
})();
